name: DisLink
version: 1.0.0
main: shake_1227.dislink.DisLink
api-version: 1.20
commands:
  disban:
    description: Bans a player from the server and Discord.
    usage: /disban <player> [reason]
  dispardon:
    description: Pardons a player from the server and Discord.
    usage: /dispardon <player>
  bypass:
    description: Adds or removes a player from the bypass list.
    usage: /bypass <add/remove> <player>
  reauth:
    description: Requests reauthentication for a player.
    usage: /reauth <player>
